version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./servers/raffle-server/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: .
      target: development-build-stage
      dockerfile: Dockerfile.server
    container_name: server
    environment:
      DB_HOST: pg
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
      POSTGRES_DATABASE: postgres
      SECRET_KEY: secret

    ports:
      - '3005:3005'
    volumes:
      - ./servers/raffle-server:/app/servers/raffle-server
      - /app/servers/raffle-server/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local


